package view;

import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import model.SessionInformation;
import view.Tab;

import serverCommunication.ServerCommunication;



/*
	 * To change this license header, choose License Headers in Project Properties.
	 * To change this template file, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/**
	 *
	 * @author user
	 */

	@SuppressWarnings("serial")
	public class VariableLoanGUI extends Tab {

		Socket socket =null;
	    /**1
	     * Creates new form index1
	     */
	    public VariableLoanGUI() {
			super("Simulation à taux variable",3);
	        
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jTabbedPane2 = new javax.swing.JTabbedPane();
	        buttonGroup1 = new javax.swing.ButtonGroup();
	        jPanel1 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jTabbedPane11 = new javax.swing.JTabbedPane();
	        jPanel8 = new javax.swing.JPanel();
	        jLabel11 = new javax.swing.JLabel();
	        jLabel12 = new javax.swing.JLabel();
	        jLabel13 = new javax.swing.JLabel();
	        typeofloan = new javax.swing.JComboBox<>();
	        jLabel14 = new javax.swing.JLabel();
	        delay = new javax.swing.JTextField();
	        jLabel15 = new javax.swing.JLabel();
	        jLabel16 = new javax.swing.JLabel();
	        capital = new javax.swing.JTextField();
	        jLabel18 = new javax.swing.JLabel();
	        jLabel19 = new javax.swing.JLabel();
	        jLabel20 = new javax.swing.JLabel();
	        jLabel21 = new javax.swing.JLabel();
	        applicationfee = new javax.swing.JTextField();
	        insurance = new javax.swing.JTextField();
	        submitscenario = new javax.swing.JButton();
	        cancel = new javax.swing.JButton();
	        yes = new javax.swing.JRadioButton();
	        no = new javax.swing.JRadioButton();
	        jLabel17 = new javax.swing.JLabel();
	        rate = new javax.swing.JLabel();
	        date = new javax.swing.JTextField();
	        pourcentage = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        accountnumber = new javax.swing.JComboBox<>();

	        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 153));
	        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 49, 148))); // NOI18N
	        jTabbedPane2.getAccessibleContext().setAccessibleName("Comparaison des prêt");

	        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setPreferredSize(new java.awt.Dimension(1200, 950));

	        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
	        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1000));

	        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
	        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
	        jLabel1.setText("Banque d'échange Mutualiste");

	        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
	        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
	        //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("username.png"))); // NOI18N
	        jLabel2.setText("Nom de l'utilisateur");

	        jTabbedPane11.setBackground(new java.awt.Color(51, 0, 0));
	        jTabbedPane11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

	        jPanel8.setBackground(new java.awt.Color(0, 51, 51));

	        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
	        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel11.setText("Simuler des scénarios d'évolution de prêts à taux variable ");

	        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel12.setText("Numéro de compte:");

	        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel13.setText("Type de prêt:");

	        

	        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel14.setText("Durée du prêt:");

	        delay.setText("\n");
	        delay.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                delayActionPerformed(evt);
	            }
	        });

	        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel15.setText("Date de première echéance:");

	        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel16.setText("Montant du prêt:");

	        capital.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                capitalActionPerformed(evt);
	            }
	        });

	        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel18.setText("Cette année le taux d'intérêt est fixé à :");

	        jLabel19.setBackground(new java.awt.Color(51, 0, 51));
	        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
	        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel19.setText("Intérêts de la banque");

	        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel20.setText("Frais de dossier:");

	        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel21.setText("Assurance:");

	        applicationfee.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                applicationfeeActionPerformed(evt);
	            }
	        });

	        insurance.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                insuranceActionPerformed(evt);
	            }
	        });

	        submitscenario.setText("Lancer");
	        submitscenario.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                submitscenarioActionPerformed(evt);
	            }
	        });

	        cancel.setText("Annuler");
	        cancel.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cancelActionPerformed(evt);
	            }
	        });

	        yes.setBackground(new java.awt.Color(0, 153, 153));
	        yes.setForeground(new java.awt.Color(255, 255, 255));
	        yes.setText("vrai");
	        yes.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                yesActionPerformed(evt);
	            }
	        });

	        no.setBackground(new java.awt.Color(0, 153, 153));
	        no.setForeground(new java.awt.Color(255, 255, 255));
	        no.setText("Faux");

	        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel17.setText("Prêt réel:");

	        rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        rate.setForeground(new java.awt.Color(255, 255, 255));	        
	        

	        pourcentage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        pourcentage.setForeground(new java.awt.Color(255, 255, 255));
	        pourcentage.setText("%");

	        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
	        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
	        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
	        jLabel3.setText("Taux d'intérêt annuel");
	        
	        // This decription it's for add a arraylist of account number
	        
	         ArrayList<String> listnumber = new ArrayList<String>();
	         ArrayList<String> arrayOftypeLoan = new ArrayList<String>();
	         float valueofrate;
	         ServerCommunication communication = new ServerCommunication();
	      
	         listnumber = communication.getAllAcounts(socket);
	         arrayOftypeLoan=communication.getAlltypeofLoan(socket);
	         valueofrate=communication.getrate();
	         
	         accountnumber.addItem("");
	         typeofloan.addItem("");
	         rate.setText(Float.toString(valueofrate));
	         for(String string : arrayOftypeLoan){
	        	 typeofloan.addItem(string);
	         }
	         
	         for(String string : listnumber){
	        	 accountnumber.addItem(string);
	         }
	       
	        accountnumber.setEditable(true);
	      accountnumber.setSelectedIndex(0);
	
	        accountnumber.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                accountnumberActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
	        jPanel8.setLayout(jPanel8Layout);
	        jPanel8Layout.setHorizontalGroup(
	            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel8Layout.createSequentialGroup()
	                .addGap(94, 94, 94)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel17)
	                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel16)
	                    .addComponent(jLabel14)
	                    .addComponent(jLabel15))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                            .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(typeofloan, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
	                            .addComponent(delay, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel8Layout.createSequentialGroup()
	                                .addComponent(submitscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(10, 10, 10))
	                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
	                                .addGap(22, 22, 22)
	                                .addComponent(yes)
	                                .addGap(38, 38, 38)
	                                .addComponent(no))
	                            .addComponent(accountnumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel8Layout.createSequentialGroup()
	                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel8Layout.createSequentialGroup()
	                                        .addGap(127, 127, 127)
	                                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                    .addGroup(jPanel8Layout.createSequentialGroup()
	                                        .addGap(222, 222, 222)
	                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel8Layout.createSequentialGroup()
	                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
	                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                .addGap(54, 54, 54))
	                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
	                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                .addGap(75, 75, 75)))
	                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                            .addComponent(insurance, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(applicationfee, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                    .addGroup(jPanel8Layout.createSequentialGroup()
	                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                        .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(pourcentage)))
	                                .addGap(167, 167, 167))))
	                    .addGroup(jPanel8Layout.createSequentialGroup()
	                        .addComponent(capital, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
	                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(157, 157, 157))))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel11)
	                .addGap(302, 302, 302))
	        );
	        jPanel8Layout.setVerticalGroup(
	            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel8Layout.createSequentialGroup()
	                .addGap(53, 53, 53)
	                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(48, 48, 48)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel12)
	                    .addComponent(accountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel3))
	                .addGap(44, 44, 44)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel8Layout.createSequentialGroup()
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel17)
	                            .addComponent(yes)
	                            .addComponent(no))
	                        .addGap(32, 32, 32)
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(typeofloan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel13))
	                        .addGap(41, 41, 41)
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel16)
	                            .addComponent(capital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(35, 35, 35))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel18)
	                            .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(pourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(58, 58, 58)
	                        .addComponent(jLabel19)
	                        .addGap(47, 47, 47)))
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel8Layout.createSequentialGroup()
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jLabel14)
	                            .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(58, 58, 58)
	                        .addComponent(jLabel15))
	                    .addGroup(jPanel8Layout.createSequentialGroup()
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(applicationfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel20))
	                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel8Layout.createSequentialGroup()
	                                .addGap(74, 74, 74)
	                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(jPanel8Layout.createSequentialGroup()
	                                .addGap(60, 60, 60)
	                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                    .addComponent(insurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel21))))))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
	                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(submitscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(168, Short.MAX_VALUE))
	        );
	        
	        // To put the current date in GUI
	        date.setText(currentDate());
	        date.setEditable(false);
	        jTabbedPane11.addTab("Prêts à taux variable", jPanel8);

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(135, 135, 135))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                .addComponent(jTabbedPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 1269, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGap(19, 19, 19)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel1)
	                    .addComponent(jLabel2))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jTabbedPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(110, Short.MAX_VALUE))
	        );

	        jLabel2.getAccessibleContext().setAccessibleName("Nom utilisateur");
	        jTabbedPane11.getAccessibleContext().setAccessibleName("lolipop");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1269, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );

	       // pack();
	    }// </editor-fold>                        

	    private void yesActionPerformed(java.awt.event.ActionEvent evt) {                                    
	        // TODO add your handling code here:
	    }                                   

	    private void submitscenarioActionPerformed(java.awt.event.ActionEvent evt) {                                               
	        // TODO add your handling code here:
	    	
	    	String accountid= (String) accountnumber.getSelectedItem();
	    	
	    	String recuploantype= (String)typeofloan.getSelectedItem();
	    	float amount= Float.parseFloat(capital.getText());

	    	int delayofloan= Integer.parseInt(delay.getText());
	    }                                              

	    private void insuranceActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        // TODO add your handling code here:
	    }                                         

	    private void applicationfeeActionPerformed(java.awt.event.ActionEvent evt) {                                               
	        // TODO add your handling code here:
	    }                                              

	    private void capitalActionPerformed(java.awt.event.ActionEvent evt) {                                        
	        // TODO add your handling code here:
	    }                                       

	    private void delayActionPerformed(java.awt.event.ActionEvent evt) {                                      
	        // TODO add your handling code here:
	    }                                     

	    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
	        // TODO add your handling code here:
	    }                                      

	    private void accountnumberActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        // TODO add your handling code here:
	    }                                             

	    public String currentDate(){
	    	DateFormat dateformat = new SimpleDateFormat();
	    	Date date = new Date();
	    	String simulationdate_hour = ""+dateformat.format(date);
	    	
	    	int prefixEnd = simulationdate_hour.indexOf(' ');
	    	String dateofsimulation = simulationdate_hour.substring(0,prefixEnd);
	    	
	    	this.date.setText(dateofsimulation);

	    	return dateofsimulation;
	    }
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(VariableLoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(VariableLoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(VariableLoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(VariableLoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new VariableLoanGUI().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JComboBox<String> accountnumber;
	    private javax.swing.JTextField applicationfee;
	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.JButton cancel;
	    private javax.swing.JTextField capital;
	    private javax.swing.JTextField date;
	    private javax.swing.JTextField delay;
	    private javax.swing.JTextField insurance;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel14;
	    private javax.swing.JLabel jLabel15;
	    private javax.swing.JLabel jLabel16;
	    private javax.swing.JLabel jLabel17;
	    private javax.swing.JLabel jLabel18;
	    private javax.swing.JLabel jLabel19;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel20;
	    private javax.swing.JLabel jLabel21;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel8;
	    private javax.swing.JTabbedPane jTabbedPane11;
	    private javax.swing.JTabbedPane jTabbedPane2;
	    private javax.swing.JRadioButton no;
	    private javax.swing.JLabel pourcentage;
	    private javax.swing.JLabel rate;
	    private javax.swing.JButton submitscenario;
	    private javax.swing.JComboBox<String> typeofloan;
	    private javax.swing.JRadioButton yes;
	    
		public void setSessionInformation(SessionInformation sessionInformation) {
		 socket =	sessionInformation.getSocket();
		 initComponents();
			
		}
		
		
	    // End of variables declaration                   
	}



